from non_terminals import NT

#CLIMACO

# table_ll1 = [[NT.S.value, 'IDENTIFIER', None ],
#          [NT.S.value, 'INT', [NT.TT.value,'IDENTIFIER',NT.D.value] ],
#          [NT.S.value, 'FLOAT', [NT.TT.value,'IDENTIFIER',NT.D.value] ],
#          [NT.S.value, 'COMMA', None],
#          [NT.S.value, 'SEMICOLON', None],
#          [NT.TT.value, 'IDENTIFIER', None ],
#          [NT.TT.value, 'INT', ['INT'] ],
#          [NT.TT.value, 'FLOAT', ['FLOAT'] ],
#          [NT.TT.value, 'COMMA', None],
#          [NT.TT.value, 'SEMICOLON', None],
#          [NT.D.value, 'IDENTIFIER', None ],
#          [NT.D.value, 'INT', None ],
#          [NT.D.value, 'FLOAT', None ],
#          [NT.D.value, 'COMMA', ['COMMA','IDENTIFIER',NT.D.value]],
#          [NT.D.value, 'SEMICOLON', ['SEMICOLON']],
#          ]
 

# DECLARATIONS 

table_ll1 = [
    [NT.DD.value, "ID", None],
    [NT.DD.value, "INT", [NT.D.value,NT.DD.value]],
    [NT.DD.value, "FLOAT", [NT.D.value,NT.DD.value]],
    [NT.DD.value, "COMMA", None],
    [NT.DD.value, "SEMICOLON", None],
    [NT.DD.value, "EOF", ['empty']],
    [NT.D.value, "ID", None],
    [NT.D.value, "INT", [NT.T.value,"IDENTIFIER",NT.DI.value]],
    [NT.D.value, "FLOAT", [NT.T.value,"IDENTIFIER",NT.DI.value]],
    [NT.D.value, "COMMA", None],
    [NT.D.value, "SEMICOLON", None],
    [NT.D.value, "EOF", None],
    [NT.T.value, "ID", None],
    [NT.T.value, "INT", ["INT"]],
    [NT.T.value, "FLOAT", ["FLOAT"]],
    [NT.T.value, "COMMA", None],
    [NT.T.value, "SEMICOLON", None],
    [NT.T.value, "EOF", None],
    [NT.DI.value, "ID", None],
    [NT.DI.value, "INT", None],
    [NT.DI.value, "FLOAT", None],
    [NT.DI.value, "COMMA", ["COMMA","IDENTIFIER",NT.DI.value]],
    [NT.DI.value, "SEMICOLON", ["SEMICOLON"]],
    [NT.DI.value, "EOF", None],
]

# table_ll1 = [
#     [NT.IF_ELSE.value, "IF", ["IF", "LPAREN", NT.CONDITION.value, "RPAREN", "LCURL", NT.STATEMENT.value, "RCURL", NT.ELSE_ST.value]],
#     [NT.IF_ELSE.value, "LPAREN", None],
#     [NT.IF_ELSE.value,"RPAREN", None],
#     [NT.IF_ELSE.value, "LCURL", None],
#     [NT.IF_ELSE.value, "RCURL", None],
#     [NT.IF_ELSE.value, "ELSE", None],
#     [NT.IF_ELSE.value, "STATEMENT", None], 
#     [NT.IF_ELSE.value, "IDENTIFIER", None],
#     [NT.IF_ELSE.value, "CHAR_LITERAL", None],
#     [NT.IF_ELSE.value, "FLOAT_LITERAL", None],
#     [NT.IF_ELSE.value, "INTEGER_LITERAL", None],
#     [NT.IF_ELSE.value, "ADD", None],
#     [NT.IF_ELSE.value, "SUB", None],
#     [NT.IF_ELSE.value, "DIV", None],
#     [NT.IF_ELSE.value, "MULT", None],
#     [NT.IF_ELSE.value, "CONJUNCTION", None],
#     [NT.IF_ELSE.value, "DISJUNCTION", None],
#     [NT.IF_ELSE.value, "EXCLAMATION", None],

#     [NT.ELSE_ST.value, "IF", None],
#     [NT.ELSE_ST.value, "LPAREN", None],
#     [NT.ELSE_ST.value,"RPAREN", None],
#     [NT.ELSE_ST.value, "LCURL", None],
#     [NT.ELSE_ST.value, "RCURL", None],
#     [NT.ELSE_ST.value, "ELSE", ["ELSE","LCURL",NT.STATEMENT.value,"RCURL"]],
#     [NT.ELSE_ST.value, "STATEMENT", None], 
#     [NT.ELSE_ST.value, "IDENTIFIER", None],
#     [NT.ELSE_ST.value, "CHAR_LITERAL", None],
#     [NT.ELSE_ST.value, "FLOAT_LITERAL", None],
#     [NT.ELSE_ST.value, "INTEGER_LITERAL", None],
#     [NT.ELSE_ST.value, "ADD", None],
#     [NT.ELSE_ST.value, "SUB", None],
#     [NT.ELSE_ST.value, "DIV", None],
#     [NT.ELSE_ST.value, "MULT", None],
#     [NT.ELSE_ST.value, "CONJUNCTION", None],
#     [NT.ELSE_ST.value, "DISJUNCTION", None],
#     [NT.ELSE_ST.value, "EXCLAMATION", None],
    
#     [NT.STATEMENT.value, "IF", None],
#     [NT.STATEMENT.value, "LPAREN", None],
#     [NT.STATEMENT.value,"RPAREN", None],
#     [NT.STATEMENT.value, "LCURL", None],
#     [NT.STATEMENT.value, "RCURL", None],
#     [NT.STATEMENT.value, "ELSE", None],
#     [NT.STATEMENT.value, "STATEMENT", ["statement"]], 
#     [NT.STATEMENT.value, "IDENTIFIER", None],
#     [NT.STATEMENT.value, "CHAR_LITERAL", None],
#     [NT.STATEMENT.value, "FLOAT_LITERAL", None],
#     [NT.STATEMENT.value, "INTEGER_LITERAL", None],
#     [NT.STATEMENT.value, "ADD", None],
#     [NT.STATEMENT.value, "SUB", None],
#     [NT.STATEMENT.value, "DIV", None],
#     [NT.STATEMENT.value, "MULT", None],
#     [NT.STATEMENT.value, "CONJUNCTION", None],
#     [NT.STATEMENT.value, "DISJUNCTION", None],
#     [NT.STATEMENT.value, "EXCLAMATION", None],

#     [NT.CONDITION.value, "IF", None],
#     [NT.CONDITION.value, "LPAREN", [NT.NEGATION.value,NT.EXPRESSION.value,NT.CONDITION_P.value]],
#     [NT.CONDITION.value,"RPAREN", [NT.NEGATION.value,NT.EXPRESSION.value,NT.CONDITION_P.value]],
#     [NT.CONDITION.value, "LCURL", None],
#     [NT.CONDITION.value, "RCURL", None],
#     [NT.CONDITION.value, "ELSE", None],
#     [NT.CONDITION.value, "STATEMENT", None], 
#     [NT.CONDITION.value, "IDENTIFIER", [NT.NEGATION.value,NT.EXPRESSION.value,NT.CONDITION_P.value]],
#     [NT.CONDITION.value, "CHAR_LITERAL", [NT.NEGATION.value,NT.EXPRESSION.value,NT.CONDITION_P.value]],
#     [NT.CONDITION.value, "FLOAT_LITERAL", [NT.NEGATION.value,NT.EXPRESSION.value,NT.CONDITION_P.value]],
#     [NT.CONDITION.value, "INTEGER_LITERAL", [NT.NEGATION.value,NT.EXPRESSION.value,NT.CONDITION_P.value]],
#     [NT.CONDITION.value, "ADD", None],
#     [NT.CONDITION.value, "SUB", None],
#     [NT.CONDITION.value, "DIV", None],
#     [NT.CONDITION.value, "MULT", None],
#     [NT.CONDITION.value, "CONJUNCTION", None],
#     [NT.CONDITION.value, "DISJUNCTION", None],
#     [NT.CONDITION.value, "EXCLAMATION", [NT.NEGATION.value,NT.EXPRESSION.value,NT.CONDITION_P.value]],

#     [NT.CONDITION_P.value, "IF", None],
#     [NT.CONDITION_P.value, "LPAREN", None],
#     [NT.CONDITION_P.value,"RPAREN", ["empty"]],
#     [NT.CONDITION_P.value, "LCURL", None],
#     [NT.CONDITION_P.value, "RCURL", None],
#     [NT.CONDITION_P.value, "ELSE", None],
#     [NT.CONDITION_P.value, "STATEMENT", None], 
#     [NT.CONDITION_P.value, "IDENTIFIER", None],
#     [NT.CONDITION_P.value, "CHAR_LITERAL", None],
#     [NT.CONDITION_P.value, "FLOAT_LITERAL", None],
#     [NT.CONDITION_P.value, "INTEGER_LITERAL", None],
#     [NT.CONDITION_P.value, "ADD", None],
#     [NT.CONDITION_P.value, "SUB", None],
#     [NT.CONDITION_P.value, "DIV", None],
#     [NT.CONDITION_P.value, "MULT", None],
#     [NT.CONDITION_P.value, "CONJUNCTION", [NT.OP_LOGIC.value,NT.NEGATION.value,NT.EXPRESSION.value,NT.CONDITION_P.value]],
#     [NT.CONDITION_P.value, "DISJUNCTION", [NT.OP_LOGIC.value,NT.NEGATION.value,NT.EXPRESSION.value,NT.CONDITION_P.value]],
#     [NT.CONDITION_P.value, "EXCLAMATION", None],

#     [NT.EXPRESSION.value, "IF", None],
#     [NT.EXPRESSION.value, "LPAREN", [NT.WITH_PAREN.value, NT.EXPRESSION_P.value]],
#     [NT.EXPRESSION.value,"RPAREN", None],
#     [NT.EXPRESSION.value, "LCURL", None],
#     [NT.EXPRESSION.value, "RCURL", None],
#     [NT.EXPRESSION.value, "ELSE", None],
#     [NT.EXPRESSION.value, "STATEMENT", None], 
#     [NT.EXPRESSION.value, "IDENTIFIER", [NT.WITH_PAREN.value, NT.EXPRESSION_P.value]],
#     [NT.EXPRESSION.value, "CHAR_LITERAL", [NT.WITH_PAREN.value, NT.EXPRESSION_P.value]],
#     [NT.EXPRESSION.value, "FLOAT_LITERAL", [NT.WITH_PAREN.value, NT.EXPRESSION_P.value]],
#     [NT.EXPRESSION.value, "INTEGER_LITERAL", [NT.WITH_PAREN.value, NT.EXPRESSION_P.value]],
#     [NT.EXPRESSION.value, "ADD", None],
#     [NT.EXPRESSION.value, "SUB", None],
#     [NT.EXPRESSION.value, "DIV", None],
#     [NT.EXPRESSION.value, "MULT", None],
#     [NT.EXPRESSION.value, "CONJUNCTION", None],
#     [NT.EXPRESSION.value, "DISJUNCTION", None],
#     [NT.EXPRESSION.value, "EXCLAMATION", None],

#     [NT.EXPRESSION_P.value, "IF", None],
#     [NT.EXPRESSION_P.value, "LPAREN", None],
#     [NT.EXPRESSION_P.value,"RPAREN", ["empty"]],
#     [NT.EXPRESSION_P.value, "LCURL", None],
#     [NT.EXPRESSION_P.value, "RCURL", None],
#     [NT.EXPRESSION_P.value, "ELSE", None],
#     [NT.EXPRESSION_P.value, "STATEMENT", None], 
#     [NT.EXPRESSION_P.value, "IDENTIFIER", None],
#     [NT.EXPRESSION_P.value, "CHAR_LITERAL", None],
#     [NT.EXPRESSION_P.value, "FLOAT_LITERAL", None],
#     [NT.EXPRESSION_P.value, "INTEGER_LITERAL", None],
#     [NT.EXPRESSION_P.value, "ADD", [NT.OP_ARI.value,NT.WITH_PAREN.value,NT.EXPRESSION_P.value]],
#     [NT.EXPRESSION_P.value, "SUB", [NT.OP_ARI.value,NT.WITH_PAREN.value,NT.EXPRESSION_P.value]],
#     [NT.EXPRESSION_P.value, "DIV", [NT.OP_ARI.value,NT.WITH_PAREN.value,NT.EXPRESSION_P.value]],
#     [NT.EXPRESSION_P.value, "MULT", [NT.OP_ARI.value,NT.WITH_PAREN.value,NT.EXPRESSION_P.value]],
#     [NT.EXPRESSION_P.value, "CONJUNCTION", ["empty"]],
#     [NT.EXPRESSION_P.value, "DISJUNCTION", ["empty"]],
#     [NT.EXPRESSION_P.value, "EXCLAMATION", None],

#     [NT.WITH_PAREN.value, "IF", None],
#     [NT.WITH_PAREN.value, "LPAREN", ["LPAREN",NT.EXPRESSION.value],"RPAREN"],
#     [NT.WITH_PAREN.value,"RPAREN", None],
#     [NT.WITH_PAREN.value, "LCURL", None],
#     [NT.WITH_PAREN.value, "RCURL", None],
#     [NT.WITH_PAREN.value, "ELSE", None],
#     [NT.WITH_PAREN.value, "STATEMENT", None], 
#     [NT.WITH_PAREN.value, "IDENTIFIER", [NT.VALUES.value]],
#     [NT.WITH_PAREN.value, "CHAR_LITERAL", [NT.VALUES.value]],
#     [NT.WITH_PAREN.value, "FLOAT_LITERAL", [NT.VALUES.value]],
#     [NT.WITH_PAREN.value, "INTEGER_LITERAL", [NT.VALUES.value]],
#     [NT.WITH_PAREN.value, "ADD", None],
#     [NT.WITH_PAREN.value, "SUB", None],
#     [NT.WITH_PAREN.value, "DIV", None],
#     [NT.WITH_PAREN.value, "MULT", None],
#     [NT.WITH_PAREN.value, "CONJUNCTION", None],
#     [NT.WITH_PAREN.value, "DISJUNCTION", None],
#     [NT.WITH_PAREN.value, "EXCLAMATION", None],

#     [NT.VALUES.value, "IF", None],
#     [NT.VALUES.value, "LPAREN", None],
#     [NT.VALUES.value,"RPAREN", None],
#     [NT.VALUES.value, "LCURL", None],
#     [NT.VALUES.value, "RCURL", None],
#     [NT.VALUES.value, "ELSE", None],
#     [NT.VALUES.value, "STATEMENT", None], 
#     [NT.VALUES.value, "IDENTIFIER", ["IDENTIFIER"]],
#     [NT.VALUES.value, "CHAR_LITERAL", ["CHAR_LITERAL"]],
#     [NT.VALUES.value, "FLOAT_LITERAL", ["FLOAT_LITERAL"]],
#     [NT.VALUES.value, "INTEGER_LITERAL", ["INTEGER_LITERAL"]],
#     [NT.VALUES.value, "ADD", None],
#     [NT.VALUES.value, "SUB", None],
#     [NT.VALUES.value, "DIV", None],
#     [NT.VALUES.value, "MULT", None],
#     [NT.VALUES.value, "CONJUNCTION", None],
#     [NT.VALUES.value, "DISJUNCTION", None],
#     [NT.VALUES.value, "EXCLAMATION", None],

#     [NT.OP_ARI.value, "IF", None],
#     [NT.OP_ARI.value, "LPAREN", None],
#     [NT.OP_ARI.value,"RPAREN", None],
#     [NT.OP_ARI.value, "LCURL", None],
#     [NT.OP_ARI.value, "RCURL", None],
#     [NT.OP_ARI.value, "ELSE", None],
#     [NT.OP_ARI.value, "STATEMENT", None], 
#     [NT.OP_ARI.value, "IDENTIFIER", None],
#     [NT.OP_ARI.value, "CHAR_LITERAL", None],
#     [NT.OP_ARI.value, "FLOAT_LITERAL", None],
#     [NT.OP_ARI.value, "INTEGER_LITERAL", None],
#     [NT.OP_ARI.value, "ADD", ["ADD"]],
#     [NT.OP_ARI.value, "SUB", ["SUB"]],
#     [NT.OP_ARI.value, "DIV", ["DIV"]],
#     [NT.OP_ARI.value, "MULT", ["MULT"]],
#     [NT.OP_ARI.value, "CONJUNCTION", None],
#     [NT.OP_ARI.value, "DISJUNCTION", None],
#     [NT.OP_ARI.value, "EXCLAMATION", None],

#     [NT.OP_LOGIC.value, "IF", None],
#     [NT.OP_LOGIC.value, "LPAREN", None],
#     [NT.OP_LOGIC.value,"RPAREN", None],
#     [NT.OP_LOGIC.value, "LCURL", None],
#     [NT.OP_LOGIC.value, "RCURL", None],
#     [NT.OP_LOGIC.value, "ELSE", None],
#     [NT.OP_LOGIC.value, "STATEMENT", None], 
#     [NT.OP_LOGIC.value, "IDENTIFIER", None],
#     [NT.OP_LOGIC.value, "CHAR_LITERAL", None],
#     [NT.OP_LOGIC.value, "FLOAT_LITERAL", None],
#     [NT.OP_LOGIC.value, "INTEGER_LITERAL", None],
#     [NT.OP_LOGIC.value, "ADD", None],
#     [NT.OP_LOGIC.value, "SUB", None],
#     [NT.OP_LOGIC.value, "DIV", None],
#     [NT.OP_LOGIC.value, "MULT", None],
#     [NT.OP_LOGIC.value, "CONJUNCTION", ["CONJUNCTION"]],
#     [NT.OP_LOGIC.value, "DISJUNCTION", ["DISJUNCTION"]],
#     [NT.OP_LOGIC.value, "EXCLAMATION", None],

#     [NT.NEGATION.value, "IF", None],
#     [NT.NEGATION.value, "LPAREN", ["empty"]],
#     [NT.NEGATION.value,"RPAREN", None],
#     [NT.NEGATION.value, "LCURL", None],
#     [NT.NEGATION.value, "RCURL", None],
#     [NT.NEGATION.value, "ELSE", None],
#     [NT.NEGATION.value, "STATEMENT", None], 
#     [NT.NEGATION.value, "IDENTIFIER", ["empty"]],
#     [NT.NEGATION.value, "CHAR_LITERAL", ["empty"]],
#     [NT.NEGATION.value, "FLOAT_LITERAL", ["empty"]],
#     [NT.NEGATION.value, "INTEGER_LITERAL", ["empty"]],
#     [NT.NEGATION.value, "ADD", None],
#     [NT.NEGATION.value, "SUB", None],
#     [NT.NEGATION.value, "DIV", None],
#     [NT.NEGATION.value, "MULT", None],
#     [NT.NEGATION.value, "CONJUNCTION", None],
#     [NT.NEGATION.value, "DISJUNCTION", None],
#     [NT.NEGATION.value, "EXCLAMATION", ["EXCLAMATION"]],
# ]
