from non_terminals import NT

# S -> Includes Globals -> [NT.Includes.value, NT.Globals.value]

# Type -> "INT" -> ["INT"]
# Type -> "FLOAT" -> ["FLOAT"]
# Type -> "CHAR" -> ["CHAR"]

# Values -> "IDENTIFIER" -> ["IDENTIFIER"]
# Values -> "CHAR_LITERAL" -> ["CHAR_LITERAL"]
# Values -> "FLOAT_LITERAL" -> ["FLOAT_LITERAL"]
# Values -> "INTEGER_LITERAL" -> ["INTEGER_LITERAL"]

# OperationAri -> "ADD" -> ["ADD"]
# OperationAri -> "SUB" -> ["SUB"]
# OperationAri -> "DIV" -> ["DIV"]
# OperationAri -> "MULT" -> ["MULT"]
# OperationLogic -> "CONJUNCTION" -> ["CONJUNCTION"]
# OperationLogic -> "DISJUNCTION" -> ["DISJUNCTION"]
# OperationLogic -> "EQUALITY" -> ["EQUALITY"]
# OperationBit -> "AMPERSAND" -> ["AMPERSAND"]
# OperationBit -> "PIPE" -> ["PIPE"]
# OperationBit -> "CIRCUMFLEX" -> ["CIRCUMFLEX"]
# OperationBit -> "LANGLE" "LANGLE" -> ["LANGLE", "LANGLE"]
# OperationBit -> "RANGLE" "RANGLE" -> ["RANGLE", "RANGLE"]

# Includes -> "PREPROCESSOR" "LANGLE" "IDENTIFIER" "DOT" "IDENTIFIER" "RANGLE" Includes -> ["PREPROCESSOR", "LANGLE", "IDENTIFIER", "DOT", "IDENTIFIER", "RANGLE", NT.Includes.value]
# Includes -> '' -> ["empty"]

# Globals -> Type "IDENTIFIER" GlobalsStartTypeId Globals -> [NT.Type.value, "IDENTIFIER", NT.GlobalsStartTypeId.value, NT.Globals.value]
# Globals -> VoidFunction Globals -> [NT.VoidFunction.value, NT.Globals.value]
# Globals -> '' -> ["empty"]

# GlobalsStartTypeId -> DeclarationsForm "SEMICOLON" -> [NT.DeclarationsForm.value, "SEMICOLON"]
# GlobalsStartTypeId -> Function -> [NT.Function.value]

# DeclarationsForm -> "COMMA" "IDENTIFIER" DeclarationsForm -> ["COMMA", "IDENTIFIER", NT.DeclarationsForm.value]
# DeclarationsForm -> "ASSIGNMENT" Expression Declarator -> ["ASSIGNMENT", NT.Expression.value, NT.Declarator.value]
# DeclarationsForm -> '' -> ["empty"]

# Declarator -> "COMMA" "IDENTIFIER" DeclarationsForm -> ["COMMA", "IDENTIFIER", NT.DeclarationsForm.value]
# Declarator -> '' -> ["empty"]

# Function -> "LPAREN" Params "RPAREN" "LCURL" Statement "RCURL" -> ["LPAREN", NT.Params.value, "RPAREN", "LCURL", NT.Statement.value, "RCURL"]

# VoidFunction -> "VOID" "IDENTIFIER" "LPAREN" Params "RPAREN" "LCURL" Statement "RCURL" -> ["VOID", "IDENTIFIER", "LPAREN", NT.Params.value, "RPAREN", "LCURL", NT.Statement.value, "RCURL"]

# Params -> Type "IDENTIFIER" ParamMulti -> [NT.Type.value, "IDENTIFIER", NT.ParamMulti.value]
# ParamMulti -> "COMMA" Params -> ["COMMA", NT.Params.value]
# ParamMulti -> '' -> ["empty"]

# Expression -> InitialExpression ExpressionPrime -> [NT.InitialExpression.value, NT.ExpressionPrime.value]

# InitialExpression -> Values -> [NT.Values.value]
# InitialExpression -> "LPAREN" Expression "RPAREN"  -> ["LPAREN", NT.Expression.value, "RPAREN"]
# InitialExpression -> "EXCLAMATION" MultpleExclamation -> ["EXCLAMATION", NT.MultpleExclamation.value]

# MultpleExclamation -> "EXCLAMATION" MultpleExclamation -> ["EXCLAMATION", NT.MultpleExclamation.value]
# MultpleExclamation -> Values -> [NT.Values.value]
# MultpleExclamation -> "LPAREN" Expression "RPAREN" -> ["LPAREN", NT.Expression.value, "RPAREN"]

# ExpressionPrime -> OperationAri Expression -> [NT.OperationAri.value, NT.Expression.value]
# ExpressionPrime -> OperationLogic Expression -> [NT.OperationLogic.value, NT.Expression.value]
# ExpressionPrime -> OperationBit Expression -> [NT.OperationBit.value, NT.Expression.value]
# ExpressionPrime -> '' -> ["empty"]

# Statement -> Type "IDENTIFIER" DeclarationsForm "SEMICOLON" Statement -> [NT.Type.value, "IDENTIFIER", NT.DeclarationsForm.value, "SEMICOLON", NT.Statement.value]
# Statement -> "IDENTIFIER" StatementStartId -> ["IDENTIFIER", NT.StatementStartId.value]
# Statement -> IfElse Statement -> [NT.IfElse.value, NT.Statement.value]
# Statement -> While Statement -> [NT.While.value, NT.Statement.value]
# Statement -> "RETURN" StatementReturn "SEMICOLON" -> ["RETURN", NT.StatementReturn.value, "SEMICOLON"]
# Statement -> '' -> ["empty"]

# StatementStartId -> Assignation "SEMICOLON" Statement -> [NT.Assignation.value, "SEMICOLON", NT.Statement.value]
# StatementStartId -> CallFunction "SEMICOLON" Statement -> [NT.CallFunction.value, "SEMICOLON", NT.Statement.value]

# StatementReturn -> Expression -> [NT.Expression.value]
# StatementReturn -> '' -> ["empty"]

# Assignation -> "ASSIGNMENT" Expression -> ["ASSIGNMENT", NT.Expression.value]

# CallFunction -> "LPAREN" CallFunctionArg "RPAREN" -> ["LPAREN", NT.CallFunctionArg.value, "RPAREN"]

# CallFunctionArg -> Expression ArgumentsMulti -> [NT.Expression.value, NT.ArgumentsMulti.value]
# CallFunctionArg -> '' -> ["empty"]

# ArgumentsMulti -> "COMMA" Expression ArgumentsMulti -> ["COMMA", NT.Expression.value, NT.ArgumentsMulti.value]
# ArgumentsMulti -> '' -> ["empty"]

# While -> "WHILE" "LPAREN" Expression "RPAREN" "LCURL" Statement "RCURL" -> ["WHILE", "LPAREN", NT.Expression.value, "RPAREN", "LCURL", NT.Statement.value, "RCURL"]

# IfElse -> "IF" "LPAREN" Expression "RPAREN" "LCURL" Statement "RCURL" "ELSE" "LCURL" Statement "RCURL" -> ["IF", "LPAREN", NT.Expression.value, "RPAREN", "LCURL", NT.Statement.value, "RCURL", "ELSE", "LCURL", NT.Statement.value, "RCURL"]


table_ll1 = [
[NT.S.value, "VOID", [NT.Includes.value, NT.Globals.value]],
[NT.S.value, "INT", [NT.Includes.value, NT.Globals.value]],
[NT.S.value, "CHAR", [NT.Includes.value, NT.Globals.value]],
[NT.S.value, "FLOAT", [NT.Includes.value, NT.Globals.value]],
[NT.S.value, "IF", None],
[NT.S.value, "ELSE", None],
[NT.S.value, "FUNCTION", None],
[NT.S.value, "WHILE", None],
[NT.S.value, "CONTINUE", None],
[NT.S.value, "BREAK", None],
[NT.S.value, "RETURN", None],
[NT.S.value, "PREPROCESSOR", [NT.Includes.value, NT.Globals.value]],
[NT.S.value, "MULT", None],
[NT.S.value, "DIV", None],
[NT.S.value, "ADD", None],
[NT.S.value, "SUB", None],
[NT.S.value, "AMPERSAND", None],
[NT.S.value, "PIPE", None],
[NT.S.value, "CIRCUMFLEX", None],
[NT.S.value, "BITNOT", None],
[NT.S.value, "LPAREN", None],
[NT.S.value, "RPAREN", None],
[NT.S.value, "LCURL", None],
[NT.S.value, "RCURL", None],
[NT.S.value, "SEMICOLON", None],
[NT.S.value, "COMMA", None],
[NT.S.value, "DOT", None],
[NT.S.value, "ASSIGNMENT", None],
[NT.S.value, "LANGLE", None],
[NT.S.value, "RANGLE", None],
[NT.S.value, "EQUALITY", None],
[NT.S.value, "CONJUNCTION", None],
[NT.S.value, "DISJUNCTION", None],
[NT.S.value, "EXCLAMATION", None],
[NT.S.value, "IDENTIFIER", None],
[NT.S.value, "FLOAT_LITERAL", None],
[NT.S.value, "INTEGER_LITERAL", None],
[NT.S.value, "CHAR_LITERAL", None],
[NT.S.value, "EOF", [NT.Includes.value, NT.Globals.value]],

[NT.Type.value, "VOID", None],
[NT.Type.value, "INT", ["INT"]],
[NT.Type.value, "CHAR", ["CHAR"]],
[NT.Type.value, "FLOAT", ["FLOAT"]],
[NT.Type.value, "IF", None],
[NT.Type.value, "ELSE", None],
[NT.Type.value, "FUNCTION", None],
[NT.Type.value, "WHILE", None],
[NT.Type.value, "CONTINUE", None],
[NT.Type.value, "BREAK", None],
[NT.Type.value, "RETURN", None],
[NT.Type.value, "PREPROCESSOR", None],
[NT.Type.value, "MULT", None],
[NT.Type.value, "DIV", None],
[NT.Type.value, "ADD", None],
[NT.Type.value, "SUB", None],
[NT.Type.value, "AMPERSAND", None],
[NT.Type.value, "PIPE", None],
[NT.Type.value, "CIRCUMFLEX", None],
[NT.Type.value, "BITNOT", None],
[NT.Type.value, "LPAREN", None],
[NT.Type.value, "RPAREN", None],
[NT.Type.value, "LCURL", None],
[NT.Type.value, "RCURL", None],
[NT.Type.value, "SEMICOLON", None],
[NT.Type.value, "COMMA", None],
[NT.Type.value, "DOT", None],
[NT.Type.value, "ASSIGNMENT", None],
[NT.Type.value, "LANGLE", None],
[NT.Type.value, "RANGLE", None],
[NT.Type.value, "EQUALITY", None],
[NT.Type.value, "CONJUNCTION", None],
[NT.Type.value, "DISJUNCTION", None],
[NT.Type.value, "EXCLAMATION", None],
[NT.Type.value, "IDENTIFIER", None],
[NT.Type.value, "FLOAT_LITERAL", None],
[NT.Type.value, "INTEGER_LITERAL", None],
[NT.Type.value, "CHAR_LITERAL", None],
[NT.Type.value, "EOF", None],

[NT.Values.value, "VOID", None],
[NT.Values.value, "INT", None],
[NT.Values.value, "CHAR", None],
[NT.Values.value, "FLOAT", None],
[NT.Values.value, "IF", None],
[NT.Values.value, "ELSE", None],
[NT.Values.value, "FUNCTION", None],
[NT.Values.value, "WHILE", None],
[NT.Values.value, "CONTINUE", None],
[NT.Values.value, "BREAK", None],
[NT.Values.value, "RETURN", None],
[NT.Values.value, "PREPROCESSOR", None],
[NT.Values.value, "MULT", None],
[NT.Values.value, "DIV", None],
[NT.Values.value, "ADD", None],
[NT.Values.value, "SUB", None],
[NT.Values.value, "AMPERSAND", None],
[NT.Values.value, "PIPE", None],
[NT.Values.value, "CIRCUMFLEX", None],
[NT.Values.value, "BITNOT", None],
[NT.Values.value, "LPAREN", None],
[NT.Values.value, "RPAREN", None],
[NT.Values.value, "LCURL", None],
[NT.Values.value, "RCURL", None],
[NT.Values.value, "SEMICOLON", None],
[NT.Values.value, "COMMA", None],
[NT.Values.value, "DOT", None],
[NT.Values.value, "ASSIGNMENT", None],
[NT.Values.value, "LANGLE", None],
[NT.Values.value, "RANGLE", None],
[NT.Values.value, "EQUALITY", None],
[NT.Values.value, "CONJUNCTION", None],
[NT.Values.value, "DISJUNCTION", None],
[NT.Values.value, "EXCLAMATION", None],
[NT.Values.value, "IDENTIFIER", ["IDENTIFIER"]],
[NT.Values.value, "FLOAT_LITERAL", ["FLOAT_LITERAL"]],
[NT.Values.value, "INTEGER_LITERAL", ["INTEGER_LITERAL"]],
[NT.Values.value, "CHAR_LITERAL", ["CHAR_LITERAL"]],
[NT.Values.value, "EOF", None],

[NT.OperationAri.value, "VOID", None],
[NT.OperationAri.value, "INT", None],
[NT.OperationAri.value, "CHAR", None],
[NT.OperationAri.value, "FLOAT", None],
[NT.OperationAri.value, "IF", None],
[NT.OperationAri.value, "ELSE", None],
[NT.OperationAri.value, "FUNCTION", None],
[NT.OperationAri.value, "WHILE", None],
[NT.OperationAri.value, "CONTINUE", None],
[NT.OperationAri.value, "BREAK", None],
[NT.OperationAri.value, "RETURN", None],
[NT.OperationAri.value, "PREPROCESSOR", None],
[NT.OperationAri.value, "MULT", ["MULT"]],
[NT.OperationAri.value, "DIV", ["DIV"]],
[NT.OperationAri.value, "ADD", ["ADD"]],
[NT.OperationAri.value, "SUB", ["SUB"]],
[NT.OperationAri.value, "AMPERSAND", None],
[NT.OperationAri.value, "PIPE", None],
[NT.OperationAri.value, "CIRCUMFLEX", None],
[NT.OperationAri.value, "BITNOT", None],
[NT.OperationAri.value, "LPAREN", None],
[NT.OperationAri.value, "RPAREN", None],
[NT.OperationAri.value, "LCURL", None],
[NT.OperationAri.value, "RCURL", None],
[NT.OperationAri.value, "SEMICOLON", None],
[NT.OperationAri.value, "COMMA", None],
[NT.OperationAri.value, "DOT", None],
[NT.OperationAri.value, "ASSIGNMENT", None],
[NT.OperationAri.value, "LANGLE", None],
[NT.OperationAri.value, "RANGLE", None],
[NT.OperationAri.value, "EQUALITY", None],
[NT.OperationAri.value, "CONJUNCTION", None],
[NT.OperationAri.value, "DISJUNCTION", None],
[NT.OperationAri.value, "EXCLAMATION", None],
[NT.OperationAri.value, "IDENTIFIER", None],
[NT.OperationAri.value, "FLOAT_LITERAL", None],
[NT.OperationAri.value, "INTEGER_LITERAL", None],
[NT.OperationAri.value, "CHAR_LITERAL", None],
[NT.OperationAri.value, "EOF", None],

[NT.OperationLogic.value, "VOID", None],
[NT.OperationLogic.value, "INT", None],
[NT.OperationLogic.value, "CHAR", None],
[NT.OperationLogic.value, "FLOAT", None],
[NT.OperationLogic.value, "IF", None],
[NT.OperationLogic.value, "ELSE", None],
[NT.OperationLogic.value, "FUNCTION", None],
[NT.OperationLogic.value, "WHILE", None],
[NT.OperationLogic.value, "CONTINUE", None],
[NT.OperationLogic.value, "BREAK", None],
[NT.OperationLogic.value, "RETURN", None],
[NT.OperationLogic.value, "PREPROCESSOR", None],
[NT.OperationLogic.value, "MULT", None],
[NT.OperationLogic.value, "DIV", None],
[NT.OperationLogic.value, "ADD", None],
[NT.OperationLogic.value, "SUB", None],
[NT.OperationLogic.value, "AMPERSAND", None],
[NT.OperationLogic.value, "PIPE", None],
[NT.OperationLogic.value, "CIRCUMFLEX", None],
[NT.OperationLogic.value, "BITNOT", None],
[NT.OperationLogic.value, "LPAREN", None],
[NT.OperationLogic.value, "RPAREN", None],
[NT.OperationLogic.value, "LCURL", None],
[NT.OperationLogic.value, "RCURL", None],
[NT.OperationLogic.value, "SEMICOLON", None],
[NT.OperationLogic.value, "COMMA", None],
[NT.OperationLogic.value, "DOT", None],
[NT.OperationLogic.value, "ASSIGNMENT", None],
[NT.OperationLogic.value, "LANGLE", None],
[NT.OperationLogic.value, "RANGLE", None],
[NT.OperationLogic.value, "EQUALITY", None],
[NT.OperationLogic.value, "CONJUNCTION", ["CONJUNCTION"]],
[NT.OperationLogic.value, "DISJUNCTION", ["DISJUNCTION"]],
[NT.OperationLogic.value, "EXCLAMATION", ["EXCLAMATION"]],
[NT.OperationLogic.value, "IDENTIFIER", None],
[NT.OperationLogic.value, "FLOAT_LITERAL", None],
[NT.OperationLogic.value, "INTEGER_LITERAL", None],
[NT.OperationLogic.value, "CHAR_LITERAL", None],
[NT.OperationLogic.value, "EOF", None],

[NT.Operationbit.value, "VOID", None],
[NT.Operationbit.value, "INT", None],
[NT.Operationbit.value, "CHAR", None],
[NT.Operationbit.value, "FLOAT", None],
[NT.Operationbit.value, "IF", None],
[NT.Operationbit.value, "ELSE", None],
[NT.Operationbit.value, "FUNCTION", None],
[NT.Operationbit.value, "WHILE", None],
[NT.Operationbit.value, "CONTINUE", None],
[NT.Operationbit.value, "BREAK", None],
[NT.Operationbit.value, "RETURN", None],
[NT.Operationbit.value, "PREPROCESSOR", None],
[NT.Operationbit.value, "MULT", None],
[NT.Operationbit.value, "DIV", None],
[NT.Operationbit.value, "ADD", None],
[NT.Operationbit.value, "SUB", None],
[NT.Operationbit.value, "AMPERSAND", ["EXCLAMATION"]],
[NT.Operationbit.value, "PIPE", ["PIPE"]],
[NT.Operationbit.value, "CIRCUMFLEX", ["CIRCUMFLEX"]],
[NT.Operationbit.value, "BITNOT", None],
[NT.Operationbit.value, "LPAREN", None],
[NT.Operationbit.value, "RPAREN", None],
[NT.Operationbit.value, "LCURL", None],
[NT.Operationbit.value, "RCURL", None],
[NT.Operationbit.value, "SEMICOLON", None],
[NT.Operationbit.value, "COMMA", None],
[NT.Operationbit.value, "DOT", None],
[NT.Operationbit.value, "ASSIGNMENT", None],
[NT.Operationbit.value, "LANGLE", ["LANGLE", "LANGLE"]],
[NT.Operationbit.value, "RANGLE", ["RANGLE", "RANGLE"]],
[NT.Operationbit.value, "EQUALITY", None],
[NT.Operationbit.value, "CONJUNCTION", None],
[NT.Operationbit.value, "DISJUNCTION", None],
[NT.Operationbit.value, "EXCLAMATION", None],
[NT.Operationbit.value, "IDENTIFIER", None],
[NT.Operationbit.value, "FLOAT_LITERAL", None],
[NT.Operationbit.value, "INTEGER_LITERAL", None],
[NT.Operationbit.value, "CHAR_LITERAL", None],
[NT.Operationbit.value, "EOF", None],

[NT.Includes.value, "VOID", ["empty"]],
[NT.Includes.value, "INT", ["empty"]],
[NT.Includes.value, "CHAR", ["empty"]],
[NT.Includes.value, "FLOAT", ["empty"]],
[NT.Includes.value, "IF", None],
[NT.Includes.value, "ELSE", None],
[NT.Includes.value, "FUNCTION", None],
[NT.Includes.value, "WHILE", None],
[NT.Includes.value, "CONTINUE", None],
[NT.Includes.value, "BREAK", None],
[NT.Includes.value, "RETURN", None],
[NT.Includes.value, "PREPROCESSOR", ["PREPROCESSOR", "LANGLE", "IDENTIFIER", "DOT", "IDENTIFIER", "RANGLE", NT.Includes.value]],
[NT.Includes.value, "MULT", None],
[NT.Includes.value, "DIV", None],
[NT.Includes.value, "ADD", None],
[NT.Includes.value, "SUB", None],
[NT.Includes.value, "AMPERSAND", None],
[NT.Includes.value, "PIPE", None],
[NT.Includes.value, "CIRCUMFLEX", None],
[NT.Includes.value, "BITNOT", None],
[NT.Includes.value, "LPAREN", None],
[NT.Includes.value, "RPAREN", None],
[NT.Includes.value, "LCURL", None],
[NT.Includes.value, "RCURL", None],
[NT.Includes.value, "SEMICOLON", None],
[NT.Includes.value, "COMMA", None],
[NT.Includes.value, "DOT", None],
[NT.Includes.value, "ASSIGNMENT", None],
[NT.Includes.value, "LANGLE", None],
[NT.Includes.value, "RANGLE", None],
[NT.Includes.value, "EQUALITY", None],
[NT.Includes.value, "CONJUNCTION", None],
[NT.Includes.value, "DISJUNCTION", None],
[NT.Includes.value, "EXCLAMATION", None],
[NT.Includes.value, "IDENTIFIER", None],
[NT.Includes.value, "FLOAT_LITERAL", None],
[NT.Includes.value, "INTEGER_LITERAL", None],
[NT.Includes.value, "CHAR_LITERAL", None],
[NT.Includes.value, "EOF", ["empty"]],

[NT.Globals.value, "VOID", [NT.VoidFunction.value, NT.Globals.value]],
[NT.Globals.value, "INT", [NT.Type.value, "IDENTIFIER", NT.GlobalsStartTypeId.value, NT.Globals.value]],
[NT.Globals.value, "CHAR", [NT.Type.value, "IDENTIFIER", NT.GlobalsStartTypeId.value, NT.Globals.value]],
[NT.Globals.value, "FLOAT", [NT.Type.value, "IDENTIFIER", NT.GlobalsStartTypeId.value, NT.Globals.value]],
[NT.Globals.value, "IF", None],
[NT.Globals.value, "ELSE", None],
[NT.Globals.value, "FUNCTION", None],
[NT.Globals.value, "WHILE", None],
[NT.Globals.value, "CONTINUE", None],
[NT.Globals.value, "BREAK", None],
[NT.Globals.value, "RETURN", None],
[NT.Globals.value, "PREPROCESSOR", None],
[NT.Globals.value, "MULT", None],
[NT.Globals.value, "DIV", None],
[NT.Globals.value, "ADD", None],
[NT.Globals.value, "SUB", None],
[NT.Globals.value, "AMPERSAND", None],
[NT.Globals.value, "PIPE", None],
[NT.Globals.value, "CIRCUMFLEX", None],
[NT.Globals.value, "BITNOT", None],
[NT.Globals.value, "LPAREN", None],
[NT.Globals.value, "RPAREN", None],
[NT.Globals.value, "LCURL", None],
[NT.Globals.value, "RCURL", None],
[NT.Globals.value, "SEMICOLON", None],
[NT.Globals.value, "COMMA", None],
[NT.Globals.value, "DOT", None],
[NT.Globals.value, "ASSIGNMENT", None],
[NT.Globals.value, "LANGLE", None],
[NT.Globals.value, "RANGLE", None],
[NT.Globals.value, "EQUALITY", None],
[NT.Globals.value, "CONJUNCTION", None],
[NT.Globals.value, "DISJUNCTION", None],
[NT.Globals.value, "EXCLAMATION", None],
[NT.Globals.value, "IDENTIFIER", None],
[NT.Globals.value, "FLOAT_LITERAL", None],
[NT.Globals.value, "INTEGER_LITERAL", None],
[NT.Globals.value, "CHAR_LITERAL", None],
[NT.Globals.value, "EOF", ["empty"]],

[NT.GlobalsStartTypeId.value, "VOID", [NT.DeclarationsForm.value, "SEMICOLON"]],
[NT.GlobalsStartTypeId.value, "INT", [NT.DeclarationsForm.value, "SEMICOLON"]],
[NT.GlobalsStartTypeId.value, "CHAR", [NT.DeclarationsForm.value, "SEMICOLON"]],
[NT.GlobalsStartTypeId.value, "FLOAT", [NT.DeclarationsForm.value, "SEMICOLON"]],
[NT.GlobalsStartTypeId.value, "IF", None],
[NT.GlobalsStartTypeId.value, "ELSE", None],
[NT.GlobalsStartTypeId.value, "FUNCTION", None],
[NT.GlobalsStartTypeId.value, "WHILE", None],
[NT.GlobalsStartTypeId.value, "CONTINUE", None],
[NT.GlobalsStartTypeId.value, "BREAK", None],
[NT.GlobalsStartTypeId.value, "RETURN", None],
[NT.GlobalsStartTypeId.value, "PREPROCESSOR", None],
[NT.GlobalsStartTypeId.value, "MULT", None],
[NT.GlobalsStartTypeId.value, "DIV", None],
[NT.GlobalsStartTypeId.value, "ADD", None],
[NT.GlobalsStartTypeId.value, "SUB", None],
[NT.GlobalsStartTypeId.value, "AMPERSAND", None],
[NT.GlobalsStartTypeId.value, "PIPE", None],
[NT.GlobalsStartTypeId.value, "CIRCUMFLEX", None],
[NT.GlobalsStartTypeId.value, "BITNOT", None],
[NT.GlobalsStartTypeId.value, "LPAREN", [NT.Function.value]],
[NT.GlobalsStartTypeId.value, "RPAREN", None],
[NT.GlobalsStartTypeId.value, "LCURL", None],
[NT.GlobalsStartTypeId.value, "RCURL", None],
[NT.GlobalsStartTypeId.value, "SEMICOLON", [NT.DeclarationsForm.value, "SEMICOLON"]],
[NT.GlobalsStartTypeId.value, "COMMA", [NT.DeclarationsForm.value, "SEMICOLON"]],
[NT.GlobalsStartTypeId.value, "DOT", None],
[NT.GlobalsStartTypeId.value, "ASSIGNMENT", [NT.DeclarationsForm.value, "SEMICOLON"]],
[NT.GlobalsStartTypeId.value, "LANGLE", None],
[NT.GlobalsStartTypeId.value, "RANGLE", None],
[NT.GlobalsStartTypeId.value, "EQUALITY", None],
[NT.GlobalsStartTypeId.value, "CONJUNCTION", None],
[NT.GlobalsStartTypeId.value, "DISJUNCTION", None],
[NT.GlobalsStartTypeId.value, "EXCLAMATION", None],
[NT.GlobalsStartTypeId.value, "IDENTIFIER", None],
[NT.GlobalsStartTypeId.value, "FLOAT_LITERAL", None],
[NT.GlobalsStartTypeId.value, "INTEGER_LITERAL", None],
[NT.GlobalsStartTypeId.value, "CHAR_LITERAL", None],
[NT.GlobalsStartTypeId.value, "EOF", [NT.DeclarationsForm.value, "SEMICOLON"]],

[NT.DeclarationsForm.value, "VOID", None],
[NT.DeclarationsForm.value, "INT", None],
[NT.DeclarationsForm.value, "CHAR", None],
[NT.DeclarationsForm.value, "FLOAT", None],
[NT.DeclarationsForm.value, "IF", None],
[NT.DeclarationsForm.value, "ELSE", None],
[NT.DeclarationsForm.value, "FUNCTION", None],
[NT.DeclarationsForm.value, "WHILE", None],
[NT.DeclarationsForm.value, "CONTINUE", None],
[NT.DeclarationsForm.value, "BREAK", None],
[NT.DeclarationsForm.value, "RETURN", None],
[NT.DeclarationsForm.value, "PREPROCESSOR", None],
[NT.DeclarationsForm.value, "MULT", None],
[NT.DeclarationsForm.value, "DIV", None],
[NT.DeclarationsForm.value, "ADD", None],
[NT.DeclarationsForm.value, "SUB", None],
[NT.DeclarationsForm.value, "AMPERSAND", None],
[NT.DeclarationsForm.value, "PIPE", None],
[NT.DeclarationsForm.value, "CIRCUMFLEX", None],
[NT.DeclarationsForm.value, "BITNOT", None],
[NT.DeclarationsForm.value, "LPAREN", None],
[NT.DeclarationsForm.value, "RPAREN", None],
[NT.DeclarationsForm.value, "LCURL", None],
[NT.DeclarationsForm.value, "RCURL", None],
[NT.DeclarationsForm.value, "SEMICOLON", None],
[NT.DeclarationsForm.value, "COMMA", None],
[NT.DeclarationsForm.value, "DOT", None],
[NT.DeclarationsForm.value, "ASSIGNMENT", None],
[NT.DeclarationsForm.value, "LANGLE", None],
[NT.DeclarationsForm.value, "RANGLE", None],
[NT.DeclarationsForm.value, "EQUALITY", None],
[NT.DeclarationsForm.value, "CONJUNCTION", None],
[NT.DeclarationsForm.value, "DISJUNCTION", None],
[NT.DeclarationsForm.value, "EXCLAMATION", None],
[NT.DeclarationsForm.value, "IDENTIFIER", None],
[NT.DeclarationsForm.value, "FLOAT_LITERAL", None],
[NT.DeclarationsForm.value, "INTEGER_LITERAL", None],
[NT.DeclarationsForm.value, "CHAR_LITERAL", None],
[NT.DeclarationsForm.value, "EOF", None],

[NT.Declarator.value, "VOID", None],
[NT.Declarator.value, "INT", None],
[NT.Declarator.value, "CHAR", None],
[NT.Declarator.value, "FLOAT", None],
[NT.Declarator.value, "IF", None],
[NT.Declarator.value, "ELSE", None],
[NT.Declarator.value, "FUNCTION", None],
[NT.Declarator.value, "WHILE", None],
[NT.Declarator.value, "CONTINUE", None],
[NT.Declarator.value, "BREAK", None],
[NT.Declarator.value, "RETURN", None],
[NT.Declarator.value, "PREPROCESSOR", None],
[NT.Declarator.value, "MULT", None],
[NT.Declarator.value, "DIV", None],
[NT.Declarator.value, "ADD", None],
[NT.Declarator.value, "SUB", None],
[NT.Declarator.value, "AMPERSAND", None],
[NT.Declarator.value, "PIPE", None],
[NT.Declarator.value, "CIRCUMFLEX", None],
[NT.Declarator.value, "BITNOT", None],
[NT.Declarator.value, "LPAREN", None],
[NT.Declarator.value, "RPAREN", None],
[NT.Declarator.value, "LCURL", None],
[NT.Declarator.value, "RCURL", None],
[NT.Declarator.value, "SEMICOLON", None],
[NT.Declarator.value, "COMMA", None],
[NT.Declarator.value, "DOT", None],
[NT.Declarator.value, "ASSIGNMENT", None],
[NT.Declarator.value, "LANGLE", None],
[NT.Declarator.value, "RANGLE", None],
[NT.Declarator.value, "EQUALITY", None],
[NT.Declarator.value, "CONJUNCTION", None],
[NT.Declarator.value, "DISJUNCTION", None],
[NT.Declarator.value, "EXCLAMATION", None],
[NT.Declarator.value, "IDENTIFIER", None],
[NT.Declarator.value, "FLOAT_LITERAL", None],
[NT.Declarator.value, "INTEGER_LITERAL", None],
[NT.Declarator.value, "CHAR_LITERAL", None],
[NT.Declarator.value, "EOF", None],

[NT.Function.value, "VOID", None],
[NT.Function.value, "INT", None],
[NT.Function.value, "CHAR", None],
[NT.Function.value, "FLOAT", None],
[NT.Function.value, "IF", None],
[NT.Function.value, "ELSE", None],
[NT.Function.value, "FUNCTION", None],
[NT.Function.value, "WHILE", None],
[NT.Function.value, "CONTINUE", None],
[NT.Function.value, "BREAK", None],
[NT.Function.value, "RETURN", None],
[NT.Function.value, "PREPROCESSOR", None],
[NT.Function.value, "MULT", None],
[NT.Function.value, "DIV", None],
[NT.Function.value, "ADD", None],
[NT.Function.value, "SUB", None],
[NT.Function.value, "AMPERSAND", None],
[NT.Function.value, "PIPE", None],
[NT.Function.value, "CIRCUMFLEX", None],
[NT.Function.value, "BITNOT", None],
[NT.Function.value, "LPAREN", None],
[NT.Function.value, "RPAREN", None],
[NT.Function.value, "LCURL", None],
[NT.Function.value, "RCURL", None],
[NT.Function.value, "SEMICOLON", None],
[NT.Function.value, "COMMA", None],
[NT.Function.value, "DOT", None],
[NT.Function.value, "ASSIGNMENT", None],
[NT.Function.value, "LANGLE", None],
[NT.Function.value, "RANGLE", None],
[NT.Function.value, "EQUALITY", None],
[NT.Function.value, "CONJUNCTION", None],
[NT.Function.value, "DISJUNCTION", None],
[NT.Function.value, "EXCLAMATION", None],
[NT.Function.value, "IDENTIFIER", None],
[NT.Function.value, "FLOAT_LITERAL", None],
[NT.Function.value, "INTEGER_LITERAL", None],
[NT.Function.value, "CHAR_LITERAL", None],
[NT.Function.value, "EOF", None],

[NT.VoidFunction.value, "VOID", None],
[NT.VoidFunction.value, "INT", None],
[NT.VoidFunction.value, "CHAR", None],
[NT.VoidFunction.value, "FLOAT", None],
[NT.VoidFunction.value, "IF", None],
[NT.VoidFunction.value, "ELSE", None],
[NT.VoidFunction.value, "FUNCTION", None],
[NT.VoidFunction.value, "WHILE", None],
[NT.VoidFunction.value, "CONTINUE", None],
[NT.VoidFunction.value, "BREAK", None],
[NT.VoidFunction.value, "RETURN", None],
[NT.VoidFunction.value, "PREPROCESSOR", None],
[NT.VoidFunction.value, "MULT", None],
[NT.VoidFunction.value, "DIV", None],
[NT.VoidFunction.value, "ADD", None],
[NT.VoidFunction.value, "SUB", None],
[NT.VoidFunction.value, "AMPERSAND", None],
[NT.VoidFunction.value, "PIPE", None],
[NT.VoidFunction.value, "CIRCUMFLEX", None],
[NT.VoidFunction.value, "BITNOT", None],
[NT.VoidFunction.value, "LPAREN", None],
[NT.VoidFunction.value, "RPAREN", None],
[NT.VoidFunction.value, "LCURL", None],
[NT.VoidFunction.value, "RCURL", None],
[NT.VoidFunction.value, "SEMICOLON", None],
[NT.VoidFunction.value, "COMMA", None],
[NT.VoidFunction.value, "DOT", None],
[NT.VoidFunction.value, "ASSIGNMENT", None],
[NT.VoidFunction.value, "LANGLE", None],
[NT.VoidFunction.value, "RANGLE", None],
[NT.VoidFunction.value, "EQUALITY", None],
[NT.VoidFunction.value, "CONJUNCTION", None],
[NT.VoidFunction.value, "DISJUNCTION", None],
[NT.VoidFunction.value, "EXCLAMATION", None],
[NT.VoidFunction.value, "IDENTIFIER", None],
[NT.VoidFunction.value, "FLOAT_LITERAL", None],
[NT.VoidFunction.value, "INTEGER_LITERAL", None],
[NT.VoidFunction.value, "CHAR_LITERAL", None],
[NT.VoidFunction.value, "EOF", None],

[NT.Params.value, "VOID", None],
[NT.Params.value, "INT", None],
[NT.Params.value, "CHAR", None],
[NT.Params.value, "FLOAT", None],
[NT.Params.value, "IF", None],
[NT.Params.value, "ELSE", None],
[NT.Params.value, "FUNCTION", None],
[NT.Params.value, "WHILE", None],
[NT.Params.value, "CONTINUE", None],
[NT.Params.value, "BREAK", None],
[NT.Params.value, "RETURN", None],
[NT.Params.value, "PREPROCESSOR", None],
[NT.Params.value, "MULT", None],
[NT.Params.value, "DIV", None],
[NT.Params.value, "ADD", None],
[NT.Params.value, "SUB", None],
[NT.Params.value, "AMPERSAND", None],
[NT.Params.value, "PIPE", None],
[NT.Params.value, "CIRCUMFLEX", None],
[NT.Params.value, "BITNOT", None],
[NT.Params.value, "LPAREN", None],
[NT.Params.value, "RPAREN", None],
[NT.Params.value, "LCURL", None],
[NT.Params.value, "RCURL", None],
[NT.Params.value, "SEMICOLON", None],
[NT.Params.value, "COMMA", None],
[NT.Params.value, "DOT", None],
[NT.Params.value, "ASSIGNMENT", None],
[NT.Params.value, "LANGLE", None],
[NT.Params.value, "RANGLE", None],
[NT.Params.value, "EQUALITY", None],
[NT.Params.value, "CONJUNCTION", None],
[NT.Params.value, "DISJUNCTION", None],
[NT.Params.value, "EXCLAMATION", None],
[NT.Params.value, "IDENTIFIER", None],
[NT.Params.value, "FLOAT_LITERAL", None],
[NT.Params.value, "INTEGER_LITERAL", None],
[NT.Params.value, "CHAR_LITERAL", None],
[NT.Params.value, "EOF", None],

[NT.ParamMulti.value, "VOID", None],
[NT.ParamMulti.value, "INT", None],
[NT.ParamMulti.value, "CHAR", None],
[NT.ParamMulti.value, "FLOAT", None],
[NT.ParamMulti.value, "IF", None],
[NT.ParamMulti.value, "ELSE", None],
[NT.ParamMulti.value, "FUNCTION", None],
[NT.ParamMulti.value, "WHILE", None],
[NT.ParamMulti.value, "CONTINUE", None],
[NT.ParamMulti.value, "BREAK", None],
[NT.ParamMulti.value, "RETURN", None],
[NT.ParamMulti.value, "PREPROCESSOR", None],
[NT.ParamMulti.value, "MULT", None],
[NT.ParamMulti.value, "DIV", None],
[NT.ParamMulti.value, "ADD", None],
[NT.ParamMulti.value, "SUB", None],
[NT.ParamMulti.value, "AMPERSAND", None],
[NT.ParamMulti.value, "PIPE", None],
[NT.ParamMulti.value, "CIRCUMFLEX", None],
[NT.ParamMulti.value, "BITNOT", None],
[NT.ParamMulti.value, "LPAREN", None],
[NT.ParamMulti.value, "RPAREN", None],
[NT.ParamMulti.value, "LCURL", None],
[NT.ParamMulti.value, "RCURL", None],
[NT.ParamMulti.value, "SEMICOLON", None],
[NT.ParamMulti.value, "COMMA", None],
[NT.ParamMulti.value, "DOT", None],
[NT.ParamMulti.value, "ASSIGNMENT", None],
[NT.ParamMulti.value, "LANGLE", None],
[NT.ParamMulti.value, "RANGLE", None],
[NT.ParamMulti.value, "EQUALITY", None],
[NT.ParamMulti.value, "CONJUNCTION", None],
[NT.ParamMulti.value, "DISJUNCTION", None],
[NT.ParamMulti.value, "EXCLAMATION", None],
[NT.ParamMulti.value, "IDENTIFIER", None],
[NT.ParamMulti.value, "FLOAT_LITERAL", None],
[NT.ParamMulti.value, "INTEGER_LITERAL", None],
[NT.ParamMulti.value, "CHAR_LITERAL", None],
[NT.ParamMulti.value, "EOF", None],

[NT.Expression.value, "VOID", None],
[NT.Expression.value, "INT", None],
[NT.Expression.value, "CHAR", None],
[NT.Expression.value, "FLOAT", None],
[NT.Expression.value, "IF", None],
[NT.Expression.value, "ELSE", None],
[NT.Expression.value, "FUNCTION", None],
[NT.Expression.value, "WHILE", None],
[NT.Expression.value, "CONTINUE", None],
[NT.Expression.value, "BREAK", None],
[NT.Expression.value, "RETURN", None],
[NT.Expression.value, "PREPROCESSOR", None],
[NT.Expression.value, "MULT", None],
[NT.Expression.value, "DIV", None],
[NT.Expression.value, "ADD", None],
[NT.Expression.value, "SUB", None],
[NT.Expression.value, "AMPERSAND", None],
[NT.Expression.value, "PIPE", None],
[NT.Expression.value, "CIRCUMFLEX", None],
[NT.Expression.value, "BITNOT", None],
[NT.Expression.value, "LPAREN", None],
[NT.Expression.value, "RPAREN", None],
[NT.Expression.value, "LCURL", None],
[NT.Expression.value, "RCURL", None],
[NT.Expression.value, "SEMICOLON", None],
[NT.Expression.value, "COMMA", None],
[NT.Expression.value, "DOT", None],
[NT.Expression.value, "ASSIGNMENT", None],
[NT.Expression.value, "LANGLE", None],
[NT.Expression.value, "RANGLE", None],
[NT.Expression.value, "EQUALITY", None],
[NT.Expression.value, "CONJUNCTION", None],
[NT.Expression.value, "DISJUNCTION", None],
[NT.Expression.value, "EXCLAMATION", None],
[NT.Expression.value, "IDENTIFIER", None],
[NT.Expression.value, "FLOAT_LITERAL", None],
[NT.Expression.value, "INTEGER_LITERAL", None],
[NT.Expression.value, "CHAR_LITERAL", None],
[NT.Expression.value, "EOF", None],

[NT.InitialExpression.value, "VOID", None],
[NT.InitialExpression.value, "INT", None],
[NT.InitialExpression.value, "CHAR", None],
[NT.InitialExpression.value, "FLOAT", None],
[NT.InitialExpression.value, "IF", None],
[NT.InitialExpression.value, "ELSE", None],
[NT.InitialExpression.value, "FUNCTION", None],
[NT.InitialExpression.value, "WHILE", None],
[NT.InitialExpression.value, "CONTINUE", None],
[NT.InitialExpression.value, "BREAK", None],
[NT.InitialExpression.value, "RETURN", None],
[NT.InitialExpression.value, "PREPROCESSOR", None],
[NT.InitialExpression.value, "MULT", None],
[NT.InitialExpression.value, "DIV", None],
[NT.InitialExpression.value, "ADD", None],
[NT.InitialExpression.value, "SUB", None],
[NT.InitialExpression.value, "AMPERSAND", None],
[NT.InitialExpression.value, "PIPE", None],
[NT.InitialExpression.value, "CIRCUMFLEX", None],
[NT.InitialExpression.value, "BITNOT", None],
[NT.InitialExpression.value, "LPAREN", None],
[NT.InitialExpression.value, "RPAREN", None],
[NT.InitialExpression.value, "LCURL", None],
[NT.InitialExpression.value, "RCURL", None],
[NT.InitialExpression.value, "SEMICOLON", None],
[NT.InitialExpression.value, "COMMA", None],
[NT.InitialExpression.value, "DOT", None],
[NT.InitialExpression.value, "ASSIGNMENT", None],
[NT.InitialExpression.value, "LANGLE", None],
[NT.InitialExpression.value, "RANGLE", None],
[NT.InitialExpression.value, "EQUALITY", None],
[NT.InitialExpression.value, "CONJUNCTION", None],
[NT.InitialExpression.value, "DISJUNCTION", None],
[NT.InitialExpression.value, "EXCLAMATION", None],
[NT.InitialExpression.value, "IDENTIFIER", None],
[NT.InitialExpression.value, "FLOAT_LITERAL", None],
[NT.InitialExpression.value, "INTEGER_LITERAL", None],
[NT.InitialExpression.value, "CHAR_LITERAL", None],
[NT.InitialExpression.value, "EOF", None],

[NT.MultpleExclamation.value, "VOID", None],
[NT.MultpleExclamation.value, "INT", None],
[NT.MultpleExclamation.value, "CHAR", None],
[NT.MultpleExclamation.value, "FLOAT", None],
[NT.MultpleExclamation.value, "IF", None],
[NT.MultpleExclamation.value, "ELSE", None],
[NT.MultpleExclamation.value, "FUNCTION", None],
[NT.MultpleExclamation.value, "WHILE", None],
[NT.MultpleExclamation.value, "CONTINUE", None],
[NT.MultpleExclamation.value, "BREAK", None],
[NT.MultpleExclamation.value, "RETURN", None],
[NT.MultpleExclamation.value, "PREPROCESSOR", None],
[NT.MultpleExclamation.value, "MULT", None],
[NT.MultpleExclamation.value, "DIV", None],
[NT.MultpleExclamation.value, "ADD", None],
[NT.MultpleExclamation.value, "SUB", None],
[NT.MultpleExclamation.value, "AMPERSAND", None],
[NT.MultpleExclamation.value, "PIPE", None],
[NT.MultpleExclamation.value, "CIRCUMFLEX", None],
[NT.MultpleExclamation.value, "BITNOT", None],
[NT.MultpleExclamation.value, "LPAREN", None],
[NT.MultpleExclamation.value, "RPAREN", None],
[NT.MultpleExclamation.value, "LCURL", None],
[NT.MultpleExclamation.value, "RCURL", None],
[NT.MultpleExclamation.value, "SEMICOLON", None],
[NT.MultpleExclamation.value, "COMMA", None],
[NT.MultpleExclamation.value, "DOT", None],
[NT.MultpleExclamation.value, "ASSIGNMENT", None],
[NT.MultpleExclamation.value, "LANGLE", None],
[NT.MultpleExclamation.value, "RANGLE", None],
[NT.MultpleExclamation.value, "EQUALITY", None],
[NT.MultpleExclamation.value, "CONJUNCTION", None],
[NT.MultpleExclamation.value, "DISJUNCTION", None],
[NT.MultpleExclamation.value, "EXCLAMATION", None],
[NT.MultpleExclamation.value, "IDENTIFIER", None],
[NT.MultpleExclamation.value, "FLOAT_LITERAL", None],
[NT.MultpleExclamation.value, "INTEGER_LITERAL", None],
[NT.MultpleExclamation.value, "CHAR_LITERAL", None],
[NT.MultpleExclamation.value, "EOF", None],

[NT.ExpressionPrime.value, "VOID", None],
[NT.ExpressionPrime.value, "INT", None],
[NT.ExpressionPrime.value, "CHAR", None],
[NT.ExpressionPrime.value, "FLOAT", None],
[NT.ExpressionPrime.value, "IF", None],
[NT.ExpressionPrime.value, "ELSE", None],
[NT.ExpressionPrime.value, "FUNCTION", None],
[NT.ExpressionPrime.value, "WHILE", None],
[NT.ExpressionPrime.value, "CONTINUE", None],
[NT.ExpressionPrime.value, "BREAK", None],
[NT.ExpressionPrime.value, "RETURN", None],
[NT.ExpressionPrime.value, "PREPROCESSOR", None],
[NT.ExpressionPrime.value, "MULT", None],
[NT.ExpressionPrime.value, "DIV", None],
[NT.ExpressionPrime.value, "ADD", None],
[NT.ExpressionPrime.value, "SUB", None],
[NT.ExpressionPrime.value, "AMPERSAND", None],
[NT.ExpressionPrime.value, "PIPE", None],
[NT.ExpressionPrime.value, "CIRCUMFLEX", None],
[NT.ExpressionPrime.value, "BITNOT", None],
[NT.ExpressionPrime.value, "LPAREN", None],
[NT.ExpressionPrime.value, "RPAREN", None],
[NT.ExpressionPrime.value, "LCURL", None],
[NT.ExpressionPrime.value, "RCURL", None],
[NT.ExpressionPrime.value, "SEMICOLON", None],
[NT.ExpressionPrime.value, "COMMA", None],
[NT.ExpressionPrime.value, "DOT", None],
[NT.ExpressionPrime.value, "ASSIGNMENT", None],
[NT.ExpressionPrime.value, "LANGLE", None],
[NT.ExpressionPrime.value, "RANGLE", None],
[NT.ExpressionPrime.value, "EQUALITY", None],
[NT.ExpressionPrime.value, "CONJUNCTION", None],
[NT.ExpressionPrime.value, "DISJUNCTION", None],
[NT.ExpressionPrime.value, "EXCLAMATION", None],
[NT.ExpressionPrime.value, "IDENTIFIER", None],
[NT.ExpressionPrime.value, "FLOAT_LITERAL", None],
[NT.ExpressionPrime.value, "INTEGER_LITERAL", None],
[NT.ExpressionPrime.value, "CHAR_LITERAL", None],
[NT.ExpressionPrime.value, "EOF", None],

[NT.Statement.value, "VOID", None],
[NT.Statement.value, "INT", None],
[NT.Statement.value, "CHAR", None],
[NT.Statement.value, "FLOAT", None],
[NT.Statement.value, "IF", None],
[NT.Statement.value, "ELSE", None],
[NT.Statement.value, "FUNCTION", None],
[NT.Statement.value, "WHILE", None],
[NT.Statement.value, "CONTINUE", None],
[NT.Statement.value, "BREAK", None],
[NT.Statement.value, "RETURN", None],
[NT.Statement.value, "PREPROCESSOR", None],
[NT.Statement.value, "MULT", None],
[NT.Statement.value, "DIV", None],
[NT.Statement.value, "ADD", None],
[NT.Statement.value, "SUB", None],
[NT.Statement.value, "AMPERSAND", None],
[NT.Statement.value, "PIPE", None],
[NT.Statement.value, "CIRCUMFLEX", None],
[NT.Statement.value, "BITNOT", None],
[NT.Statement.value, "LPAREN", None],
[NT.Statement.value, "RPAREN", None],
[NT.Statement.value, "LCURL", None],
[NT.Statement.value, "RCURL", None],
[NT.Statement.value, "SEMICOLON", None],
[NT.Statement.value, "COMMA", None],
[NT.Statement.value, "DOT", None],
[NT.Statement.value, "ASSIGNMENT", None],
[NT.Statement.value, "LANGLE", None],
[NT.Statement.value, "RANGLE", None],
[NT.Statement.value, "EQUALITY", None],
[NT.Statement.value, "CONJUNCTION", None],
[NT.Statement.value, "DISJUNCTION", None],
[NT.Statement.value, "EXCLAMATION", None],
[NT.Statement.value, "IDENTIFIER", None],
[NT.Statement.value, "FLOAT_LITERAL", None],
[NT.Statement.value, "INTEGER_LITERAL", None],
[NT.Statement.value, "CHAR_LITERAL", None],
[NT.Statement.value, "EOF", None],

[NT.StatementStartId.value, "VOID", None],
[NT.StatementStartId.value, "INT", None],
[NT.StatementStartId.value, "CHAR", None],
[NT.StatementStartId.value, "FLOAT", None],
[NT.StatementStartId.value, "IF", None],
[NT.StatementStartId.value, "ELSE", None],
[NT.StatementStartId.value, "FUNCTION", None],
[NT.StatementStartId.value, "WHILE", None],
[NT.StatementStartId.value, "CONTINUE", None],
[NT.StatementStartId.value, "BREAK", None],
[NT.StatementStartId.value, "RETURN", None],
[NT.StatementStartId.value, "PREPROCESSOR", None],
[NT.StatementStartId.value, "MULT", None],
[NT.StatementStartId.value, "DIV", None],
[NT.StatementStartId.value, "ADD", None],
[NT.StatementStartId.value, "SUB", None],
[NT.StatementStartId.value, "AMPERSAND", None],
[NT.StatementStartId.value, "PIPE", None],
[NT.StatementStartId.value, "CIRCUMFLEX", None],
[NT.StatementStartId.value, "BITNOT", None],
[NT.StatementStartId.value, "LPAREN", [NT.CallFunction.value, "SEMICOLON", NT.Statement.value]],
[NT.StatementStartId.value, "RPAREN", None],
[NT.StatementStartId.value, "LCURL", None],
[NT.StatementStartId.value, "RCURL", None],
[NT.StatementStartId.value, "SEMICOLON", None],
[NT.StatementStartId.value, "COMMA", None],
[NT.StatementStartId.value, "DOT", None],
[NT.StatementStartId.value, "ASSIGNMENT", [NT.Assignation.value, "SEMICOLON", NT.Statement.value]],
[NT.StatementStartId.value, "LANGLE", None],
[NT.StatementStartId.value, "RANGLE", None],
[NT.StatementStartId.value, "EQUALITY", None],
[NT.StatementStartId.value, "CONJUNCTION", None],
[NT.StatementStartId.value, "DISJUNCTION", None],
[NT.StatementStartId.value, "EXCLAMATION", None],
[NT.StatementStartId.value, "IDENTIFIER", None],
[NT.StatementStartId.value, "FLOAT_LITERAL", None],
[NT.StatementStartId.value, "INTEGER_LITERAL", None],
[NT.StatementStartId.value, "CHAR_LITERAL", None],
[NT.StatementStartId.value, "EOF", None],

[NT.StatementReturn.value, "VOID", None],
[NT.StatementReturn.value, "INT", None],
[NT.StatementReturn.value, "CHAR", None],
[NT.StatementReturn.value, "FLOAT", None],
[NT.StatementReturn.value, "IF", None],
[NT.StatementReturn.value, "ELSE", None],
[NT.StatementReturn.value, "FUNCTION", None],
[NT.StatementReturn.value, "WHILE", None],
[NT.StatementReturn.value, "CONTINUE", None],
[NT.StatementReturn.value, "BREAK", None],
[NT.StatementReturn.value, "RETURN", None],
[NT.StatementReturn.value, "PREPROCESSOR", None],
[NT.StatementReturn.value, "MULT", None],
[NT.StatementReturn.value, "DIV", None],
[NT.StatementReturn.value, "ADD", None],
[NT.StatementReturn.value, "SUB", None],
[NT.StatementReturn.value, "AMPERSAND", None],
[NT.StatementReturn.value, "PIPE", None],
[NT.StatementReturn.value, "CIRCUMFLEX", None],
[NT.StatementReturn.value, "BITNOT", None],
[NT.StatementReturn.value, "LPAREN", [NT.Expression.value]],
[NT.StatementReturn.value, "RPAREN", None],
[NT.StatementReturn.value, "LCURL", None],
[NT.StatementReturn.value, "RCURL", None],
[NT.StatementReturn.value, "SEMICOLON", ["empty"]],
[NT.StatementReturn.value, "COMMA", None],
[NT.StatementReturn.value, "DOT", None],
[NT.StatementReturn.value, "ASSIGNMENT", None],
[NT.StatementReturn.value, "LANGLE", None],
[NT.StatementReturn.value, "RANGLE", None],
[NT.StatementReturn.value, "EQUALITY", None],
[NT.StatementReturn.value, "CONJUNCTION", None],
[NT.StatementReturn.value, "DISJUNCTION", None],
[NT.StatementReturn.value, "EXCLAMATION", [NT.Expression.value]],
[NT.StatementReturn.value, "IDENTIFIER", [NT.Expression.value]],
[NT.StatementReturn.value, "FLOAT_LITERAL", [NT.Expression.value]],
[NT.StatementReturn.value, "INTEGER_LITERAL", [NT.Expression.value]],
[NT.StatementReturn.value, "CHAR_LITERAL", [NT.Expression.value]],
[NT.StatementReturn.value, "EOF", None],

[NT.Assignation.value, "VOID", None],
[NT.Assignation.value, "INT", None],
[NT.Assignation.value, "CHAR", None],
[NT.Assignation.value, "FLOAT", None],
[NT.Assignation.value, "IF", None],
[NT.Assignation.value, "ELSE", None],
[NT.Assignation.value, "FUNCTION", None],
[NT.Assignation.value, "WHILE", None],
[NT.Assignation.value, "CONTINUE", None],
[NT.Assignation.value, "BREAK", None],
[NT.Assignation.value, "RETURN", None],
[NT.Assignation.value, "PREPROCESSOR", None],
[NT.Assignation.value, "MULT", None],
[NT.Assignation.value, "DIV", None],
[NT.Assignation.value, "ADD", None],
[NT.Assignation.value, "SUB", None],
[NT.Assignation.value, "AMPERSAND", None],
[NT.Assignation.value, "PIPE", None],
[NT.Assignation.value, "CIRCUMFLEX", None],
[NT.Assignation.value, "BITNOT", None],
[NT.Assignation.value, "LPAREN", None],
[NT.Assignation.value, "RPAREN", None],
[NT.Assignation.value, "LCURL", None],
[NT.Assignation.value, "RCURL", None],
[NT.Assignation.value, "SEMICOLON", None],
[NT.Assignation.value, "COMMA", None],
[NT.Assignation.value, "DOT", None],
[NT.Assignation.value, "ASSIGNMENT", ["ASSIGNMENT", NT.Expression.value]],
[NT.Assignation.value, "LANGLE", None],
[NT.Assignation.value, "RANGLE", None],
[NT.Assignation.value, "EQUALITY", None],
[NT.Assignation.value, "CONJUNCTION", None],
[NT.Assignation.value, "DISJUNCTION", None],
[NT.Assignation.value, "EXCLAMATION", None],
[NT.Assignation.value, "IDENTIFIER", None],
[NT.Assignation.value, "FLOAT_LITERAL", None],
[NT.Assignation.value, "INTEGER_LITERAL", None],
[NT.Assignation.value, "CHAR_LITERAL", None],
[NT.Assignation.value, "EOF", None],

[NT.CallFunction.value, "VOID", None],
[NT.CallFunction.value, "INT", None],
[NT.CallFunction.value, "CHAR", None],
[NT.CallFunction.value, "FLOAT", None],
[NT.CallFunction.value, "IF", None],
[NT.CallFunction.value, "ELSE", None],
[NT.CallFunction.value, "FUNCTION", None],
[NT.CallFunction.value, "WHILE", None],
[NT.CallFunction.value, "CONTINUE", None],
[NT.CallFunction.value, "BREAK", None],
[NT.CallFunction.value, "RETURN", None],
[NT.CallFunction.value, "PREPROCESSOR", None],
[NT.CallFunction.value, "MULT", None],
[NT.CallFunction.value, "DIV", None],
[NT.CallFunction.value, "ADD", None],
[NT.CallFunction.value, "SUB", None],
[NT.CallFunction.value, "AMPERSAND", None],
[NT.CallFunction.value, "PIPE", None],
[NT.CallFunction.value, "CIRCUMFLEX", None],
[NT.CallFunction.value, "BITNOT", None],
[NT.CallFunction.value, "LPAREN", ["LPAREN", NT.CallFunctionArg.value, "RPAREN"]],
[NT.CallFunction.value, "RPAREN", None],
[NT.CallFunction.value, "LCURL", None],
[NT.CallFunction.value, "RCURL", None],
[NT.CallFunction.value, "SEMICOLON", None],
[NT.CallFunction.value, "COMMA", None],
[NT.CallFunction.value, "DOT", None],
[NT.CallFunction.value, "ASSIGNMENT", None],
[NT.CallFunction.value, "LANGLE", None],
[NT.CallFunction.value, "RANGLE", None],
[NT.CallFunction.value, "EQUALITY", None],
[NT.CallFunction.value, "CONJUNCTION", None],
[NT.CallFunction.value, "DISJUNCTION", None],
[NT.CallFunction.value, "EXCLAMATION", None],
[NT.CallFunction.value, "IDENTIFIER", None],
[NT.CallFunction.value, "FLOAT_LITERAL", None],
[NT.CallFunction.value, "INTEGER_LITERAL", None],
[NT.CallFunction.value, "CHAR_LITERAL", None],
[NT.CallFunction.value, "EOF", None],

[NT.CallFunctionArg.value, "VOID", None],
[NT.CallFunctionArg.value, "INT", None],
[NT.CallFunctionArg.value, "CHAR", None],
[NT.CallFunctionArg.value, "FLOAT", None],
[NT.CallFunctionArg.value, "IF", None],
[NT.CallFunctionArg.value, "ELSE", None],
[NT.CallFunctionArg.value, "FUNCTION", None],
[NT.CallFunctionArg.value, "WHILE", None],
[NT.CallFunctionArg.value, "CONTINUE", None],
[NT.CallFunctionArg.value, "BREAK", None],
[NT.CallFunctionArg.value, "RETURN", None],
[NT.CallFunctionArg.value, "PREPROCESSOR", None],
[NT.CallFunctionArg.value, "MULT", None],
[NT.CallFunctionArg.value, "DIV", None],
[NT.CallFunctionArg.value, "ADD", None],
[NT.CallFunctionArg.value, "SUB", None],
[NT.CallFunctionArg.value, "AMPERSAND", None],
[NT.CallFunctionArg.value, "PIPE", None],
[NT.CallFunctionArg.value, "CIRCUMFLEX", None],
[NT.CallFunctionArg.value, "BITNOT", None],
[NT.CallFunctionArg.value, "LPAREN", [NT.Expression.value, NT.ArgumentsMulti.value]],
[NT.CallFunctionArg.value, "RPAREN", ["empty"]],
[NT.CallFunctionArg.value, "LCURL", None],
[NT.CallFunctionArg.value, "RCURL", None],
[NT.CallFunctionArg.value, "SEMICOLON", None],
[NT.CallFunctionArg.value, "COMMA", None],
[NT.CallFunctionArg.value, "DOT", None],
[NT.CallFunctionArg.value, "ASSIGNMENT", None],
[NT.CallFunctionArg.value, "LANGLE", None],
[NT.CallFunctionArg.value, "RANGLE", None],
[NT.CallFunctionArg.value, "EQUALITY", None],
[NT.CallFunctionArg.value, "CONJUNCTION", None],
[NT.CallFunctionArg.value, "DISJUNCTION", None],
[NT.CallFunctionArg.value, "EXCLAMATION", [NT.Expression.value, NT.ArgumentsMulti.value]],
[NT.CallFunctionArg.value, "IDENTIFIER", [NT.Expression.value, NT.ArgumentsMulti.value]],
[NT.CallFunctionArg.value, "FLOAT_LITERAL", [NT.Expression.value, NT.ArgumentsMulti.value]],
[NT.CallFunctionArg.value, "INTEGER_LITERAL", [NT.Expression.value, NT.ArgumentsMulti.value]],
[NT.CallFunctionArg.value, "CHAR_LITERAL", [NT.Expression.value, NT.ArgumentsMulti.value]],
[NT.CallFunctionArg.value, "EOF", None],

[NT.ArgumentsMulti.value, "VOID", None],
[NT.ArgumentsMulti.value, "INT", None],
[NT.ArgumentsMulti.value, "CHAR", None],
[NT.ArgumentsMulti.value, "FLOAT", None],
[NT.ArgumentsMulti.value, "IF", None],
[NT.ArgumentsMulti.value, "ELSE", None],
[NT.ArgumentsMulti.value, "FUNCTION", None],
[NT.ArgumentsMulti.value, "WHILE", None],
[NT.ArgumentsMulti.value, "CONTINUE", None],
[NT.ArgumentsMulti.value, "BREAK", None],
[NT.ArgumentsMulti.value, "RETURN", None],
[NT.ArgumentsMulti.value, "PREPROCESSOR", None],
[NT.ArgumentsMulti.value, "MULT", None],
[NT.ArgumentsMulti.value, "DIV", None],
[NT.ArgumentsMulti.value, "ADD", None],
[NT.ArgumentsMulti.value, "SUB", None],
[NT.ArgumentsMulti.value, "AMPERSAND", None],
[NT.ArgumentsMulti.value, "PIPE", None],
[NT.ArgumentsMulti.value, "CIRCUMFLEX", None],
[NT.ArgumentsMulti.value, "BITNOT", None],
[NT.ArgumentsMulti.value, "LPAREN", None],
[NT.ArgumentsMulti.value, "RPAREN", ["empty"]],
[NT.ArgumentsMulti.value, "LCURL", None],
[NT.ArgumentsMulti.value, "RCURL", None],
[NT.ArgumentsMulti.value, "SEMICOLON", None],
[NT.ArgumentsMulti.value, "COMMA", ["COMMA", NT.Expression.value, NT.ArgumentsMulti.value]],
[NT.ArgumentsMulti.value, "DOT", None],
[NT.ArgumentsMulti.value, "ASSIGNMENT", None],
[NT.ArgumentsMulti.value, "LANGLE", None],
[NT.ArgumentsMulti.value, "RANGLE", None],
[NT.ArgumentsMulti.value, "EQUALITY", None],
[NT.ArgumentsMulti.value, "CONJUNCTION", None],
[NT.ArgumentsMulti.value, "DISJUNCTION", None],
[NT.ArgumentsMulti.value, "EXCLAMATION", None],
[NT.ArgumentsMulti.value, "IDENTIFIER", None],
[NT.ArgumentsMulti.value, "FLOAT_LITERAL", None],
[NT.ArgumentsMulti.value, "INTEGER_LITERAL", None],
[NT.ArgumentsMulti.value, "CHAR_LITERAL", None],
[NT.ArgumentsMulti.value, "EOF", None],

[NT.While.value, "VOID", None],
[NT.While.value, "INT", None],
[NT.While.value, "CHAR", None],
[NT.While.value, "FLOAT", None],
[NT.While.value, "IF", None],
[NT.While.value, "ELSE", None],
[NT.While.value, "FUNCTION", None],
[NT.While.value, "WHILE", ["WHILE", "LPAREN", NT.Expression.value, "RPAREN", "LCURL", NT.Statement.value, "RCURL"]],
[NT.While.value, "CONTINUE", None],
[NT.While.value, "BREAK", None],
[NT.While.value, "RETURN", None],
[NT.While.value, "PREPROCESSOR", None],
[NT.While.value, "MULT", None],
[NT.While.value, "DIV", None],
[NT.While.value, "ADD", None],
[NT.While.value, "SUB", None],
[NT.While.value, "AMPERSAND", None],
[NT.While.value, "PIPE", None],
[NT.While.value, "CIRCUMFLEX", None],
[NT.While.value, "BITNOT", None],
[NT.While.value, "LPAREN", None],
[NT.While.value, "RPAREN", None],
[NT.While.value, "LCURL", None],
[NT.While.value, "RCURL", None],
[NT.While.value, "SEMICOLON", None],
[NT.While.value, "COMMA", None],
[NT.While.value, "DOT", None],
[NT.While.value, "ASSIGNMENT", None],
[NT.While.value, "LANGLE", None],
[NT.While.value, "RANGLE", None],
[NT.While.value, "EQUALITY", None],
[NT.While.value, "CONJUNCTION", None],
[NT.While.value, "DISJUNCTION", None],
[NT.While.value, "EXCLAMATION", None],
[NT.While.value, "IDENTIFIER", None],
[NT.While.value, "FLOAT_LITERAL", None],
[NT.While.value, "INTEGER_LITERAL", None],
[NT.While.value, "CHAR_LITERAL", None],
[NT.While.value, "EOF", None],

[NT.IfElse.value, "VOID", None],
[NT.IfElse.value, "INT", None],
[NT.IfElse.value, "CHAR", None],
[NT.IfElse.value, "FLOAT", None],
[NT.IfElse.value, "IF", ["IF", "LPAREN", NT.Expression.value, "RPAREN", "LCURL", NT.Statement.value, "RCURL", "ELSE", "LCURL", NT.Statement.value, "RCURL"]],
[NT.IfElse.value, "ELSE", None],
[NT.IfElse.value, "FUNCTION", None],
[NT.IfElse.value, "WHILE", None],
[NT.IfElse.value, "CONTINUE", None],
[NT.IfElse.value, "BREAK", None],
[NT.IfElse.value, "RETURN", None],
[NT.IfElse.value, "PREPROCESSOR", None],
[NT.IfElse.value, "MULT", None],
[NT.IfElse.value, "DIV", None],
[NT.IfElse.value, "ADD", None],
[NT.IfElse.value, "SUB", None],
[NT.IfElse.value, "AMPERSAND", None],
[NT.IfElse.value, "PIPE", None],
[NT.IfElse.value, "CIRCUMFLEX", None],
[NT.IfElse.value, "BITNOT", None],
[NT.IfElse.value, "LPAREN", None],
[NT.IfElse.value, "RPAREN", None],
[NT.IfElse.value, "LCURL", None],
[NT.IfElse.value, "RCURL", None],
[NT.IfElse.value, "SEMICOLON", None],
[NT.IfElse.value, "COMMA", None],
[NT.IfElse.value, "DOT", None],
[NT.IfElse.value, "ASSIGNMENT", None],
[NT.IfElse.value, "LANGLE", None],
[NT.IfElse.value, "RANGLE", None],
[NT.IfElse.value, "EQUALITY", None],
[NT.IfElse.value, "CONJUNCTION", None],
[NT.IfElse.value, "DISJUNCTION", None],
[NT.IfElse.value, "EXCLAMATION", None],
[NT.IfElse.value, "IDENTIFIER", None],
[NT.IfElse.value, "FLOAT_LITERAL", None],
[NT.IfElse.value, "INTEGER_LITERAL", None],
[NT.IfElse.value, "CHAR_LITERAL", None],
[NT.IfElse.value, "EOF", None]
]